import CoreGraphics
import CoreText
import Foundation

private let baseWidth = 8
private let baseHeight = 12
private let scales = [1, 2, 3]

private func rasterize(_ character: Character, scale: Int) -> [UInt8] {
    let width = baseWidth * scale
    let height = baseHeight * scale
    var pixels = [UInt8](repeating: 0, count: width * height)
    let colorSpace = CGColorSpaceCreateDeviceGray()

    pixels.withUnsafeMutableBytes { bytes in
        guard let context = CGContext(data: bytes.baseAddress,
                                      width: width,
                                      height: height,
                                      bitsPerComponent: 8,
                                      bytesPerRow: width,
                                      space: colorSpace,
                                      bitmapInfo: CGImageAlphaInfo.none.rawValue) else {
            fatalError("Unable to create font bitmap context")
        }

        context.setFillColor(gray: 0, alpha: 1)
        context.fill(CGRect(x: 0, y: 0, width: width, height: height))
        context.setFillColor(gray: 1, alpha: 1)
        context.setAllowsAntialiasing(true)
        context.setShouldAntialias(true)
        context.setShouldSmoothFonts(true)

        let pointSize = CGFloat(10 * scale)
        let font = CTFontCreateUIFontForLanguage(.userFixedPitch, pointSize, nil)
            ?? CTFontCreateWithName("Menlo-Regular" as CFString, pointSize, nil)
        let attributes: [CFString: Any] = [
            kCTFontAttributeName: font,
            kCTForegroundColorFromContextAttributeName: true
        ]
        let string = NSAttributedString(string: String(character), attributes: attributes as [NSAttributedString.Key: Any])
        let line = CTLineCreateWithAttributedString(string)
        var ascent: CGFloat = 0
        var descent: CGFloat = 0
        var leading: CGFloat = 0
        let lineWidth = CGFloat(CTLineGetTypographicBounds(line, &ascent, &descent, &leading))
        let x = max(0, (CGFloat(width) - lineWidth) / 2)
        let baseline = max(descent, (CGFloat(height) - ascent - descent) / 2 + descent)
        context.textPosition = CGPoint(x: x, y: baseline)
        CTLineDraw(line, context)
    }

    return pixels
}

private func emitArray(scale: Int) {
    let width = baseWidth * scale
    let height = baseHeight * scale
    print("const uint8_t nova_font_alpha_\(scale)[96][\(width * height)] = {")
    for code in 32...127 {
        let character = Character(UnicodeScalar(code)!)
        let pixels = rasterize(character, scale: scale)
        print("    {")
        for row in 0..<height {
            let values = pixels[(row * width)..<((row + 1) * width)]
                .map { String(format: "%3d", $0) }
                .joined(separator: ", ")
            print("        \(values),")
        }
        print("    },")
    }
    print("};\n")
}

print("#include \"types.h\"")
print("\n/* Generated by tools/generate_font.swift from macOS's antialiased UI mono face. */\n")
for scale in scales {
    emitArray(scale: scale)
}
